export const TOGGLE_DROPDOWN = 'TOGGLE_DROPDOWN';
export const CLOSE_DROPDOWN = 'CLOSE_DROPDOWN';
export const SET_CART_ID = 'SET_CART_ID';
export const SET_CART_ITEMS = 'SET_CART_ITEMS';
export const SET_CART_INITIAL = 'SET_CART_INITIAL';
