export const TOGGLE_DROPDOWN = 'TOGGLE_DROPDOWN';
export const CLOSE_DROPDOWN = 'CLOSE_DROPDOWN';
export const SET_CART_ID = 'SET_CART_ID';
export const SET_CART_ITEMS = 'SET_CART_ITEMS';
export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const CLEAR_ITEM_FROM_CART = 'CLEAR_ITEM_FROM_CART';
export const SET_CART_INITIAL = 'SET_CART_INITIAL';
